#!/bin/bash

usage() {
        echo "Usage :"
        echo "   ZonePolicy-enable        : $0 y" >&2
        echo "   ZonePolicy-disable       : $0 n" >&2
        echo "   Activation state   : $0 info" >&2
        exit 1
}

nowstate()
{
    if [ -f /etc/pam.d/systemd-user.bak ]
    then
        echo "enabled"
    else
        echo "disabled"
    fi
}

zoneenable()
{
    if [ `nowstate` = "enabled" ]
    then
        echo "Already zone-enabled";
        exit 0
    fi

    /bin/mv /etc/pam.d/systemd-user /etc/pam.d/systemd-user.bak
    /bin/cp /etc/pam.d/systemd-user-zone /etc/pam.d/systemd-user
    /bin/sync
}

zonedisable()
{
    if [ `nowstate` = "disabled" ]
    then
        echo "Already zone-disabled";
        exit 0
    fi

    /bin/mv /etc/pam.d/systemd-user.bak /etc/pam.d/systemd-user
    /bin/sync
}

if [ $EUID -ne 0 ]; then
   echo "Root permission is required." 1>&2
   exit 1
fi

case "${1}" in
"y"|"Y")
        zoneenable ;;
"n"|"N")
        zonedisable ;;
"i"|"info")
        nowstate ;;
*)
        usage
esac

exit 0


